# Generated by Django 5.1.7 on 2025-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='وصف غير متاح'),
            preserve_default=False,
        ),
    ]
